# Generated by Django 2.2.24 on 2021-09-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210907_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='author_name',
            field=models.CharField(default='valera', max_length=200, verbose_name='имя автора'),
            preserve_default=False,
        ),
    ]
