# Generated by Django 2.2.24 on 2021-09-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_task_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='pub_date',
            field=models.DateField(auto_now_add=True, verbose_name='дата публикации'),
        ),
    ]
