# Generated by Django 2.2.24 on 2021-09-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default='2000-01-01', verbose_name='дата публикации'),
            preserve_default=False,
        ),
    ]
